### PR TITLE
improved about us page

### PR DESCRIPTION
**Pull request by aditya07389**
Hey @swaraj-das 
issue no #489 
I have improved the aesthetics of about us page 

https://github.com/user-attachments/assets/97a7a47d-94fb-404d-83b8-4194fa6fb625

I hope u like it 

Please add the labels gssoc extd , hacktoberfest , level 3

### CODE REVIEW

**Comment by swaraj-das** [comment]
@aditya07389 This issue doesn't qualify for level 3. I can assign it a level 2 instead.

**Review by swaraj-das — APPROVED** [review]

**Comment by aditya07389** [comment]
Okay please add the labels

**Comment by swaraj-das** [comment]
@aditya07389 Can you fix this type of animation which was implemented in the index.html?

**Comment by aditya07389** [comment]
yeah , i can raise a new issue for that @swaraj-das

**Comment by aditya07389** [comment]
please add the labels gssoc extd , hacktoberfest and level 2 , or it wont show in my gssoc leaderboard

**Comment by aditya07389** [comment]
@swaraj-das can u please add the labels gssoc extd and hacktoberfest along with an appropriate level label for this , it will be counted for leaderboard only if the labels are added 

Thankyou!

**Comment by swaraj-das** [comment]
> @swaraj-das can u please add the labels gssoc extd and hacktoberfest along with an appropriate level label for this , it will be counted for leaderboard only if the labels are added
> 
> Thankyou!

Ohh There is my mistake. I forgot to add label. Sorry.

**Comment by swaraj-das** [comment]
> yeah , i can raise a new issue for that @swaraj-das

Yes

**Pull request merged**
