### PR TITLE
Added show password buttons #180

### PR DESCRIPTION
**Pull request by devarsheecodess**
# Pull Request Format
## Type of PR
- [ X] Feature enhancement

## Description
This pull request aims to fix an issue where show password buttons were not present in login and signup pages.

## Screenshots / Videos (if applicable)
**Before:**
image
image

**After:**

https://github.com/user-attachments/assets/33a85b22-af3d-4787-97d1-4f180b21d760

## Checklist
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by devarsheecodess** [comment]
@swaraj-das plz check my PR

**Comment by swaraj-das** [comment]
@devarsheecodess There is merge conflict. please resolve it.

**Comment by devarsheecodess** [comment]
@swaraj-das i have resolved the conflicts, merge before i get more conflicts
Also add the labels here too

**Comment by swaraj-das** [comment]
@devarsheecodess There is conflict till now.

**Comment by devarsheecodess** [comment]
@swaraj-das , i have resolved the merge conflicts again, plz merge before i get more conflicts :')

**Comment by devarsheecodess** [comment]
@swaraj-das plz merge my PR with labels

**Comment by devarsheecodess** [comment]
@swaraj-das i have resolved the conflicts again, plz merge my PR

**Pull request closed without merging**
