### PR TITLE
solved button hovering issues in homepage

### LINKED ISSUE #144: [Feature] smooth hover effect for buttons
### Description

I would like to implement a smooth hover effect for buttons on the website to make the interface more visually appealing and interactive. This feature will enhance the look and feel of the website, providing users with a subtle visual feedback when they hover over buttons.

### Screenshots

https://github.com/user-attachments/assets/076ae6c7-d314-408e-85fc-715da233382e

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

### PR DESCRIPTION
**Pull request by Subashree-selvaraj**
## Resolved Alignment issues while hovering button

fixes #144  

## Type of PR

- [X] Feature enhancement

**description**:
The issue that I have resolved is while hovering the buttons(buy now and cart to cart) there rises an alignment issues of the container so I fixed this one and also added hovering effect for button in contact us section

**Before:**

https://github.com/user-attachments/assets/47c46d03-0a6a-4e82-a84a-ff07591042b5

**After:**

https://github.com/user-attachments/assets/f75853d7-983e-4890-9c29-98bf807276b2

## Checklist

- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!could you please increase the level

### CODE REVIEW

**Comment by swaraj-das** [comment]
@Subashree-selvaraj There is 2 conflicts in css. Please resolve.

**Comment by Subashree-selvaraj** [comment]
> @Subashree-selvaraj There is 2 conflicts in css. Please resolve.

RESOLVED! kindly check it

**Comment by Subashree-selvaraj** [comment]
> > @Subashree-selvaraj There is 2 conflicts in css. Please resolve.
> 
> RESOLVED! kindly check it

@swaraj-das

**Comment by swaraj-das** [comment]
> > > @Subashree-selvaraj There is 2 conflicts in css. Please resolve.
> > 
> > 
> > RESOLVED! kindly check it
> 
> @swaraj-das

I've reviewed the code. You should sync your fork and update the changes in the PR; otherwise, other styles which is implemented in code might be affected.

**Pull request closed without merging**
