### PR TITLE
PWA enabled

### PR DESCRIPTION
**Pull request by mohammedanaf**
# Pull Request Format
## Type of PR
- **Add X in the box to specify the improvement type.**
- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
This pull request aims to make the website a PWA so users can download it into their smartphones, tables, laptops or desktops and access it directly through the app icon on the system. It also provides the capability of offline viewing without compromising in quality or quantity.

## Screenshots / Videos (if applicable)
Since PWA is only supported in HTTPS connection, there is no screenshot or video showcasing the functionality.

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### Additional Context
I have modified `index.html` file with an inline comment to link `manifest.json`. I have also added two other files named `manifest.json` and `service-worker.js` for enabling PWA. I have also added a service worker script in `script.js` at the bottom with an inline comment to detect `service-worker.js` file in the root of the folder. I also have resized `logo.png` to 192x192 and 512x512 format for app icon in different screen sizes.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by mohammedanaf** [comment]
@swaraj-das I have mentioned the files which I had to modify in the `Additional Content` part of PR

**Review by AnitSarkar123 — APPROVED** [review]
Sorry @swaraj-das I didn't know anything about PWA at this time but according to copilot it is approved

**Comment by mohammedanaf** [comment]
Once the pull request gets merged and changes are reflected, this is how it's gonna look @swaraj-das @AnitSarkar123 

PWA-enabled

https://in.pinterest.com

**Comment by AnitSarkar123** [comment]
Ok as you said

**Pull request merged**
