### PR TITLE
improve preloader

### PR DESCRIPTION
**Pull request by VidhanThakur09**
# Pull Request Format
## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
Styling has been applied to the preloader. The preloader is present on all pages of the website with styling.

*Improvements:*

1. *Optimized Preloader:* Enhanced the preloader animation on the index, login/login, and signup/signup pages to improve user experience.

2. *Revamped Preloader Design:* Redesigned the preloader with modern CSS styling to enhance visual appeal.

3. *Dedicated Preloader Script and StyleSheet:* Created a separate JavaScript file named `"preloader.js"` to manage the preloader functionality and CSS file named `" preloaderStyle.css"` to enhance the styling and functionality, ensuring better code organization and maintainability.

## Screenshots 📷

**Before changes** 

Screenshot 2024-10-07 135253

**After adding preloader**

https://github.com/user-attachments/assets/260f08b5-76b1-4834-a47b-b4e368fd5408

## Checklist

- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by swaraj-das** [comment]
@VidhanThakur09
There’s a merge conflict in your PR. Please resolve it, and I’ll merge it afterward.

**Comment by VidhanThakur09** [comment]
I will do my best to resolve the conflict.

**Comment by VidhanThakur09** [comment]
Merge conflicts fixed
issue number #194 
@swaraj-das please merge this before someone edit the codebase

**Comment by VidhanThakur09** [comment]
@swaraj-das please assign this PR to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

**Comment by VidhanThakur09** [comment]
Can you assign this PR to me with labels "gssoc-ext" with level.

**Comment by VidhanThakur09** [comment]
@Suruchibharti @IshaChouhan01 @Lehak1 @Khyathi23 @Riaz340 can you please add labels and assign this PR to me

**Pull request merged**
