### PR TITLE
Added `Disclaimer Page` 

### PR DESCRIPTION
**Pull request by Adarsh-Chaubey03**
## Type of PR

- [x] Feature enhancement
  

## Description
- Added `Disclaimer Page`
- Similar To `Privacy Policy` Page
- Color Matching to website theme

## Screenshots / Videos (if applicable)
Screenshot 2024-10-21 111212

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

@swaraj-das please review my pr

### CODE REVIEW

**Comment by Adarsh-Chaubey03** [comment]
@swaraj-das please review my pr

**Comment by Adarsh-Chaubey03** [comment]
> Hi there! This issue is still open. We are looking forward to your response.
>   Assignees: None

I have been already assigned this task

**Comment by Adarsh-Chaubey03** [comment]
@swaraj-das

**Comment by Adarsh-Chaubey03** [comment]
@swaraj-das check this out

**Comment by Adarsh-Chaubey03** [comment]
@swaraj-das check this out

**Comment by Adarsh-Chaubey03** [comment]
@swaraj-das check this out

**Review by swaraj-das — APPROVED** [review]

**Pull request merged**
