### PR TITLE
Updated And Fixed Few Issues Is Style.css and script .js

### PR DESCRIPTION
**Pull request by rimmon1234**
# Pull Request Format
## Type of PR
- **Add X in the box to specify the improvement type.**
- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
This pull request aims to fix issues like CSS Variables,Redundant Code,Responsiveness,Accessibility,Performance,Performance,Scroll-to-Top Button

## Screenshots / Videos (if applicable)
**Before:**
1.the scroll to top button was visible even after being on top after reloading
2.Repeated Background Definition: The button has two background definitions, which are redundant. You only need one.
3.Not Enough Media Queries: Adding another breakpoint for larger screens, e.g., Responsiveness: Adjusted the mobile-first approach for .menu-icon and other elements. The icon is visible by default and hidden on larger screens.
4.Animations Optimization
5.Toggle Button Issue: The toggleMenu function compares the maxHeight value with "0px", which could sometimes be "0" or other forms depending on the browser and situation.
5.Inefficient DOM Access: In the scroll event listener, you repeatedly access the DOM for scrollTopButton
6.Debouncing Scroll Events: The scroll event fires multiple times per second, and updating the DOM on every scroll can impact performance. 

**After:**
1.CSS Variables: Defined common properties like gradients, dark overlay, and button hover background using :root.
2.Redundant Code: Removed redundant scrollbar styles and optimized by merging selectors.
3.Responsiveness: Adjusted the mobile-first approach for .menu-icon and other elements. The icon is visible by default and hidden on larger screens.
4.Media Queries Update: Added another breakpoint for larger screens
5.Accessibility: Added text-shadow to hero text for better visibility, included focus states for links and buttons, and ensured color contrast is sufficient.
6.Performance: The rainbow animation remains but is optimized for performance. The background image in .hero is handled carefully.
7.Scroll-to-Top Button: It’s now controlled dynamically with a class like .show that can be triggered via JavaScript when the user scrolls.
8. added window.addEventListener('load'): Which Ensures that the scroll position is checked when the page initially loads and the "Scroll to Top" button is hidden if the user is at the top.
9. Debounce on Scroll: The scroll event is debounced for better performance, preventing unnecessary updates.

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by rimmon1234** [comment]
please checkout @swaraj-das

**Comment by swaraj-das** [comment]
@rimmon1234 Merge conflicts. Please resolve it.

**Comment by rimmon1234** [comment]
Solved The Conflicts Please Merge It And Give The Appropriate Labels

**Comment by rimmon1234** [comment]
Please Check Now

**Comment by swaraj-das** [comment]
No needed. Other contributors already updated it.

**Pull request closed without merging**
