### PR TITLE
adding three files and changing nevbar#156

### PR DESCRIPTION
**Pull request by Abhishek89chauhan**
# Pull Request Format
## Type of PR
- **Add X in the box to specify the improvement type.**
- [] Bug fix
- [ X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
i had created additional web pages for VR accossories,game controlling and for other section and improving nev bar where login button is not in sequence

## Screenshots / Videos (if applicable)
**Before:**
Screenshot 2024-10-07 204927

**After:**
Screenshot 2024-10-09 104021

## Checklist
- **Add X in the box to specify.**
- [] I have performed a self-review of my code.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### Additional Context
in nev bar nev items are in a line after change it is a asequence

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by swaraj-das** [comment]
@Abhishek89chauhan Check if there is any problem with the css file.
image

**Comment by Abhishek89chauhan** [comment]
please check it out i have fix it

**Comment by Abhishek89chauhan** [comment]
Screenshot 2024-10-09 153408

**Comment by Abhishek89chauhan** [comment]
sir please give a level

**Comment by swaraj-das** [comment]
Mereg conflict. Solve that

**Pull request closed without merging**
