### PR TITLE
✨Add Visitor Counter feature done ! #643

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #643
Add Visitor Counter feature done properly -

Screenshot 2024-10-23 011058
image

Before -
Screenshot 2024-10-23 011108

## Type of PR
- **Add X in the box to specify the improvement type.**
- [ ] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): ___________  

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
PA kindly add level 3, If you check other projects, they are also giving level 3 for this..

Screenshot 2024-10-22 204511


You can check my code also...

Thank you 🙏🏻

**Comment by swaraj-das** [comment]
image

Place it at footer downside of the feedback section.

**Comment by Subhajit-2023-44** [comment]
> image
> 
> It's not reponsive. Btw, Place it at footer downside of the feedback section.

Screenshot 2024-10-23 203133

@swaraj-das here ? or 

image

here ??

**Comment by swaraj-das** [comment]
@Subhajit-2023-44 

image
Upon the copyright section , in the blank space.

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44
> 
> image Upon the copyright section , in the blank space.

Ok wait I will give new PR

**Pull request closed without merging**
