### PR TITLE
Replaced the old add-to-cart PNG file with a better one.

### PR DESCRIPTION
**Pull request by rees8**
## Type of PR
- **Add X in the box to specify the improvement type.**
- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
This PR was aimed to improve the visual appeal of the "Add To Cart" button. 

## Screenshots / Videos (if applicable)
**Before:**
image

- Here, the Add to Cart button is a "+" sign, which doesn't look visually appealing.

**After:**
image

- [Describe the state after the changes, e.g., "The section headings in the footer are now properly aligned, providing a clean and professional look."]The "Shopping Cart" symbol serves to be more practical and appealing.

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by swaraj-das** [comment]
@rees8 The icon should be white in color

**Comment by rees8** [comment]
I have updated the icon to be white, please check if it's better. @swaraj-das

**Review by swaraj-das — APPROVED** [review]
ok

**Comment by rees8** [comment]
Hello @swaraj-das, could you also assign the level tag for this PR?

**Pull request merged**
