### PR TITLE
Update social icon in the sidebar section

### PR DESCRIPTION
**Pull request by Antima2004**
update the social icon in the sidebar section

### Issue # 213: **update the social icon in the sidebar section
** solved

## Type of PR
- **Add X in the box to specify the improvement type.**
- [X] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________

### CODE REVIEW

**Comment by swaraj-das** [comment]
@Antima2004 Add hover effect like the other social icons to the X icon

**Comment by Antima2004** [comment]
ok

**Comment by swaraj-das** [comment]
merge conflict. Please resolve

**Comment by Antima2004** [comment]
@swaraj-das  i already resolve the conflict and pr is done #220

**Pull request closed without merging**
