### PR TITLE
Add Google Authentication to the Application #340

### PR DESCRIPTION
**Pull request by simmi-verma**
This PR updates the Firebase configuration by replacing hardcoded credentials with environment variables to enhance security. Sensitive keys such as apiKey, authDomain, and others are now stored in environment variables, ensuring that they are not exposed in the codebase. This also improves flexibility for different environments (e.g., development, production) by allowing the configuration to be dynamically set based on environment-specific values.

### CODE REVIEW

**Comment by simmi-verma** [comment]
I have added Google authentication

**Comment by AnitSarkar123** [comment]
> I have added Google authentication 

Demo vedio

**Review by AnitSarkar123 — COMMENTED** [review]
Everything looks good to me.. but I want a demo vedio

**Comment by simmi-verma** [comment]
okay

**Comment by AnitSarkar123** [comment]
> Thank you for your feedback! I will create a demo video showcasing the Google authentication implementation. Please let me know if there are specific features or steps you’d like me to highlight.

No

**Comment by simmi-verma** [comment]
https://github.com/user-attachments/assets/06692332-9eb6-49fd-860c-84e9134918a3

**Comment by AnitSarkar123** [comment]
@simmi-verma can you please change the login to log out if the user login already

**Comment by AnitSarkar123** [comment]
> @simmi-verma can you please change the login to log out if the user login already 

You don't required to write the functionality of logout just change  the login to logout

**Comment by simmi-verma** [comment]
Ok

**Comment by simmi-verma** [comment]
https://github.com/user-attachments/assets/edc5790b-8c31-41c6-a304-fd00adf07134
"I have changed 'Login' to 'Logout' when clicking on 'login in with Google'.

**Comment by AnitSarkar123** [comment]
@simmi-verma please give a vedio

**Comment by simmi-verma** [comment]
https://github.com/user-attachments/assets/64ffc432-2fe2-41c6-9f00-41201f5bd158

**Pull request merged**
