### PR TITLE
Issue :- #383 Solved :- Added Registration Pop up Succesfully

### PR DESCRIPTION
**Pull request by PrAyAg9**
# Pull Request Format
## Type of PR
- **Add X in the box to specify the improvement type.**
- [] Bug fix
- [X ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
This pull request aims to [briefly describe what the pull request does, e.g., "add a new feature," "fix a bug," "improve documentation," etc.]. 

## Screenshots / Videos (if applicable)
**Before:**
image
This was before when you get to landing page L- 

**After:**
image

- [Describe the state after the changes, -- You can see that I have successfully implement a pop up which will provoke user to sign up with exciting deals for first time users]

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

### Additional Context
I have seen it works fine, Check the design and it's working and inform if any inconsistencies found. Thank you.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by swaraj-das** [comment]
@PrAyAg9 The code is good and the pop up looks great. But there is a drawback. Please add a cross button to the up-right corner for closing the pop up. The pop up is not closing.

**Comment by PrAyAg9** [comment]
@swaraj-das I've done it now if user clicks anywhere outside pop up it will close and that logo was meant to be a way to close as you mention and you can also close it by clicking on no thanks.

**Comment by PrAyAg9** [comment]
@swaraj-das There was a conflict in my branch due to updation of some code in index.html, It was my first time to resolve  a conflict.
So, Please check if everything working fine as I've already updated code of popup.js and then i tried to resolve conflict, Please check if everything's working fine and if something is wrong I'll raise a new pull request. Thank you

**Review by swaraj-das — APPROVED** [review]

**Comment by swaraj-das** [comment]
> @swaraj-das There was a conflict in my branch due to updation of some code in index.html, It was my first time to resolve a conflict. So, Please check if everything working fine as I've already updated code of popup.js and then i tried to resolve conflict, Please check if everything's working fine and if something is wrong I'll raise a new pull request. Thank you

The code is well. I merged it.

**Pull request merged**
