### PR TITLE
Added the scroll to top button feature with enhanced ui and better functioning.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
# Pull Request Format
## Type of PR
- **Add X in the box to specify the improvement type.**
- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
I have properly added a scroll to top button with enhanced ui and proper design with better functioning you can check it out.

## Screenshots / Videos (if applicable)
image

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

@swaraj-das @AnitSarkar123 Please check this PR and merge it and assign this to me and put relevent labels like gssoc 2024 ext, hacktoberfest and level.

### CODE REVIEW

**Comment by tarunkumar2005** [comment]
@swaraj-das @AnitSarkar123 Please review this faster this time otherwise it will have conflicts again.

**Comment by tarunkumar2005** [comment]
Everything is correctly done i think this time no issues.

**Comment by AnitSarkar123** [comment]
> Everything is correctly done i think this time no issues.

Give it on other side or in the middle.

**Comment by tarunkumar2005** [comment]
Will do that in the center of the page I think will be good.

**Comment by AnitSarkar123** [comment]
> Will do that in the center of the page I think will be good.

Yes👍

**Comment by tarunkumar2005** [comment]
image

Is it okay @AnitSarkar123

**Comment by AnitSarkar123** [comment]
> image
> 
> Is it okay @AnitSarkar123 

Yes 👍

**Comment by AnitSarkar123** [comment]
@swaraj-das check it and merge it

**Pull request merged**
