### PR TITLE
smooth hover effect for buttons 

### LINKED ISSUE #144: [Feature] smooth hover effect for buttons
### Description

I would like to implement a smooth hover effect for buttons on the website to make the interface more visually appealing and interactive. This feature will enhance the look and feel of the website, providing users with a subtle visual feedback when they hover over buttons.

### Screenshots

https://github.com/user-attachments/assets/076ae6c7-d314-408e-85fc-715da233382e

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

### PR DESCRIPTION
**Pull request by Subashree-selvaraj**
fixes #144 

description:
The issue is will hovering the button everything in the webpage is disturbed so it is resolved now!
 This feature will enhance the look and feel of the website, providing users with a subtle visual feedback when they hover over buttons.

Before:

https://github.com/user-attachments/assets/f92f23e2-c5a3-4423-9a4d-5f0b76db244e

After:

https://github.com/user-attachments/assets/df83be28-7c23-4cd1-9c06-eadade42c2fe

## Checklist

- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X]  I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by swaraj-das** [comment]
@Subashree-selvaraj Merge conflict. Please resolve.

**Comment by Subashree-selvaraj** [comment]
> @Subashree-selvaraj Merge conflict. Please resolve.

Resolved !

**Comment by swaraj-das** [comment]
@Subashree-selvaraj
Thank you for fixing the button! However, there are still some issues with the FAQ section and a few other features. Could you please sync your fork to update the changes and then make a new PR?

**Comment by Subashree-selvaraj** [comment]
> @Subashree-selvaraj Thank you for fixing the button! However, there are still some issues with the FAQ section and a few other features. Could you please sync your fork to update the changes and then make a new PR?

Yes! raise new PR with all change that you have mentioned.kindly check it! #299

**Pull request closed without merging**
