### PR TITLE
Add a pop up dialog box for Polls/Survey done !

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
done - #724

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Checklist

- [X] I have performed a self-review of my code.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@swaraj-das

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123 please merge my PR with level 3 & gssoc-ext label

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123 please merge my PR with level 3 and gssoc-ext label 😭

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123 please merge my PR with level 3 and gssoc-ext label 😭😭

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123 please merge my PR with level 3 and gssoc-ext label 😭😭

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123

**Review by AnitSarkar123 — APPROVED** [review]

**Comment by Subhajit-2023-44** [comment]
@AnitSarkar123 @swaraj-das sir plese add level 3 and gssoc-ext label, today is the last day...

**Comment by Subhajit-2023-44** [comment]
@AnitSarkar123 @swaraj-das sir plese add level 3 and gssoc-ext label, today is the last day...

**Comment by Subhajit-2023-44** [comment]
image


@AnitSarkar123 @swaraj-das sir plese add level 3 and gssoc-ext label, today is the last day...

**Pull request merged**
