### PR TITLE
Solved issue #181. added nav bar to login and signup pages

### PR DESCRIPTION
**Pull request by manikdamle**
# Pull Request Format
## Type of PR
- [X] Bug fix

## Description
Added nav bar to login and signup pages

- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by manikdamle** [comment]
Hey @swaraj-das! Pls check and merge

**Comment by manikdamle** [comment]
@swaraj-das pls review

**Comment by swaraj-das** [comment]
@manikdamle The login page looks decent, but there’s room for improvement. The sign-up page needs more attention as it requires significant enhancements. Additionally, both the footer and the navbar don’t look quite right and could use redesigning to improve the overall user experience.

**Comment by manikdamle** [comment]
@swaraj-das Ok will do so.

**Pull request closed without merging**
