### PR TITLE
🛠️FIX :Name validation added on contact us section

### PR DESCRIPTION
**Pull request by akash70629**
# Pull Request Format
## Type of PR

- [X] Bug fix

## Description
Name validation is added to contact us section. Name Input only accepts alphabets, the field does not allow users to input symbols and special characters, which may lead to invalid or spam submissions.

## Screenshots / Videos (if applicable)
**Before:**
image

**After:**
image

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by akash70629** [comment]
Please merge this PR

**Comment by akash70629** [comment]
@swaraj-das added the validation in the `script.js` file, now please merge it and add gssoc , level 1 label .

**Comment by akash70629** [comment]
@swaraj-das please merge it .

**Comment by akash70629** [comment]
Are you there ? @swaraj-das

**Comment by akash70629** [comment]
@swaraj-das merge it !!!!!!

**Review by swaraj-das — APPROVED** [review]

**Pull request merged**
