### PR TITLE
Enhanced the 'Back' button on Login, Sign Up & Forgot Page.

### PR DESCRIPTION
**Pull request by RohanShrivastava08**
#300  
## 
## Type of PR
- [ ] Feature enhancement

## Description
This pull request aims to changes I made:
Matched the background color to the login-container (rgba(0, 0, 0, 0.8)).
Retained the smooth transitions and hover effects to make it interactive.
Added box-shadow similar to the login-container for visual consistency.
Slight transformation on hover and active states to give a modern feel.

## Screenshots / Videos (if applicable)
**Before:**

Screenshot (459)

Screenshot (460)

**After:**

Screenshot (461)

Screenshot (462)

## Checklist
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by swaraj-das** [comment]
@RohanShrivastava08 Merge conflict. Please resolve.

**Review by RohanShrivastava08 — COMMENTED** [review]
Review done successfully !

**Comment by swaraj-das** [comment]
Till there is conflict

**Comment by RohanShrivastava08** [comment]
Can you guide me once? I tried again it ran but I got this error on mail:
.github/workflows/auto-assign-action.yml: No jobs were run.
Can you help me a bit?

**Comment by swaraj-das** [comment]
> Can you guide me once? I tried again it ran but I got this error on mail: .github/workflows/auto-assign-action.yml: No jobs were run. Can you help me a bit?

There are too many conflicts. You should remove the unnecessary spaces inside the curly braces in the code. Don't worry about the 'No jobs done' message—it's due to an error in the auto-assign action within the .github/workflows/ folder.

**Pull request closed without merging**
