### PR TITLE
Create copyright.html

### PR DESCRIPTION
**Pull request by neeru24**
# Add Copyright Page

## Description
This pull request introduces a fully responsive Copyright page for the **Collect Your Gaming Tools** website. The following features and improvements have been implemented:

### Features and Improvements
- **Navbar**: Added a centered navigation bar with links to "Home," "About," and a "Switch Theme" button.
- **Dark Theme**: Implemented a dark theme for the Copyright page, ensuring a consistent user experience across the site.
- **Responsive Design**: Utilized flexbox to create a responsive layout that stacks navbar items vertically on smaller screens.
- **Hover Effects**: Added hover effects to buttons and sections for improved user interaction.
- **Copyright Sections**: Structured the page with clear sections outlining copyright notice, content ownership, trademark information, and contact details.
- **Footer**: Included a footer stating copyright information, ensuring compliance and professionalism.

### Additional Changes
- Updated CSS to enhance styling for both light and dark themes.
- Ensured all interactive elements are easily accessible and visually appealing.

## Testing
The Copyright page has been tested across various devices and screen sizes to ensure proper responsiveness and usability.

---

**Note**: Please review the code and assign me **LEVEL 3** for this @swaraj-das 
fixes: #576 

image
image
image
image

### CODE REVIEW

**Comment by AnitSarkar123** [comment]
Great job 👍

**Comment by neeru24** [comment]
> Link it with the main page

https://github.com/swaraj-das/Collect-your-GamingTools/pull/608

**Comment by AnitSarkar123** [comment]
> > Link it with the main page
> 
> Check. It. Please https://github.com/swaraj-das/Collect-your-GamingTools/pull/608

@swaraj-das please say something to her because I don't have any words to say her.

**Comment by swaraj-das** [comment]
@neeru24 **"Pull requests that only partially address an issue are not acceptable. We will only consider merging your PR if it fully resolves the issue. Submitting incomplete solutions in parts solely to gain extra points on the leaderboard is prohibited and will not be tolerated."**

**Comment by neeru24** [comment]
> @neeru24 **"Pull requests that only partially address an issue are not acceptable. We will only consider merging your PR if it fully resolves the issue. Submitting incomplete solutions in parts solely to gain extra points on the leaderboard is prohibited and will not be tolerated."**

I agree but I was assigned with the issues and I did what I mentioned in the issue like there was no page for

**Comment by swaraj-das** [comment]
> @swaraj-das please say something to her because I don't have any words to say her.

I'm shocked to see PRs submitted separately for such closely related tasks like adding links in HTML and creating the actual pages. I previously noticed someone else doing something similar. This behavior is not acceptable, and if it continues, I will have no choice but to report it to the event organizers.

**Comment by swaraj-das** [comment]
> > @neeru24 **"Pull requests that only partially address an issue are not acceptable. We will only consider merging your PR if it fully resolves the issue. Submitting incomplete solutions in parts solely to gain extra points on the leaderboard is prohibited and will not be tolerated."**
> 
> I agree but I was assigned with the issues and I did what I mentioned in the issue like there was no page for copyright and I created that and I've changed the main file too that links it with that.. So May I please know where the issue is partially addressed?

Sync your fork, and you'll find a 'policies' folder. Add all the policy HTML files there and link them in the index.

**Comment by neeru24** [comment]
> > > @neeru24 **"Pull requests that only partially address an issue are not acceptable. We will only consider merging your PR if it fully resolves the issue. Submitting incomplete solutions in parts solely to gain extra points on the leaderboard is prohibited and will not be tolerated."**
> > 
> > I agree but I was assigned with the issues and I did what I mentioned in the issue like there was no page for copyright and I created that and I've changed the main file too that links it with that.. So May I please know where the issue is partially addressed?
> 
> Sync your fork, and you'll find a 'policies' folder. Add all the policy HTML files there and link them in the index.

Okay, Thank you for helping out and please tell us before making any comment like what we are doing wrong. Many of the contributors are new to open source, so it would be better if you could guide us.

**Comment by neeru24** [comment]
> Sync your fork, and you'll find a 'policies' folder. Add all the policy HTML files there and link them in the index.

Done with the changes that you said, I added the files in policies folder and linked with index.html file too.
Kindly check and please let me know if any issues are there @swaraj-das . 

Thank you!!
image

**Pull request closed without merging**
