### PR TITLE
#419 Fix/UI fix

### PR DESCRIPTION
**Pull request by biswa2005**
# Pull Request Format
## Type of PR
- **Add X in the box to specify the improvement type.**
- [X] Bug fix
- [X] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): ___________  

## Description
fix the login page UI

## Screenshots / Videos (if applicable)
**Before:**
it was very natural somethings are very wrongly aligned

**After:**
i have redesigned the full ui of login page

## Checklist
- **Add X in the box to specify.**
Screenshot 2024-10-16 173211

- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### Additional Context
[Provide any additional context about the changes, such as specific challenges you faced or decisions you made. This can help reviewers understand the rationale behind your changes.]

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by biswa2005** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/swaraj-das/reviewers)

**Comment by AnitSarkar123** [comment]
> A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.
> 
> [Approve this user](https://app.netlify.com/teams/swaraj-das/reviewers)

Who the new user @biswa2005

**Comment by swaraj-das** [comment]
@biswa2005 Can you change the sign up page like this? 
Add some css for back button. And can you change the color of eye button into white?

**Comment by biswa2005** [comment]
Then open a new issue and then assign me in it because I cannot be able to
do changes in already merged issue

**Pull request merged**
