### PR TITLE
[FIX] Sign up button & made Responsive 

### LINKED ISSUE #232: [BUG] Sign Up page Styling Issue
## Sign Up Page Style Issue
- Home page icon is not aligned

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingToolst/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

### PR DESCRIPTION
**Pull request by 4F24L**
## Sign up button & made Responsive 
- Fixes #232

## Type of PR
**Add X in the box to specify the improvement type.**
- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
- I redesign the signup page. I made the page fit in 100Vh, so the user will not have to scroll to sign up. sign up button style changed. And was The page made responsive for smaller screens.

### **Before :**
- Sign up button issue.
- Sign up Page overflow [ scroll mode ]
- Not responsive.

 image

### **After ✅ :**
- Sign up button issue fixed.
- Sign up page overflow [ scroll mode ] Fixed.
- Made responsive.

 image

## Checklist
**Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

#### Please add level 3 to this PR. I changed the button, the page, and the form and made responsive for smaller screens

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by 4F24L** [comment]
https://deploy-preview-256--collect-your-gamingtools.netlify.app/signup/signup

Preview Here

**Comment by 4F24L** [comment]
Hey @swaraj-das , Can you review this ?!

Please add level 3 to this PR. I changed the button, the page, and the form and made responsive for smaller screens

**Comment by swaraj-das** [comment]
> Hey @swaraj-das , Can you review this ?!
> 
> Please add level 3 to this PR. I changed the button, the page, and the form and made responsive for smaller screens

It's not sufficient for Level 3. You need to work on more complex tasks to truly earn the Level 3 label. Understand?

**Review by swaraj-das — APPROVED** [review]

**Comment by 4F24L** [comment]
> > Hey @swaraj-das , Can you review this ?!
> > Please add level 3 to this PR. I changed the button, the page, and the form and made responsive for smaller screens
> 
> It's not sufficient for Level 3. You need to work on more complex tasks to truly earn the Level 3 label. Understand?

Thanks, Understood !

**Pull request merged**
