### PR TITLE
Addtocart

### PR DESCRIPTION
**Pull request by aditya07389**
hey @swaraj-das 

I have implemented the add to cart functionality kindly check 

issue no : #491

Video :

https://github.com/user-attachments/assets/8724c424-9e96-4850-82c1-2ee327a9f0ae

Kindly add the labels : gssoc extd , hacktoberfest , level

### CODE REVIEW

**Comment by aditya07389** [comment]
@swaraj-das kindly check

**Comment by swaraj-das** [comment]
@aditya07389 Your code is good. The changes are acceptable. But please don't show the cart items as pop-up. Make separate page for that.

**Comment by aditya07389** [comment]
Okay, on it

**Comment by aditya07389** [comment]
Well I made the popover because I had mentioned it in the issue! Kindly read the issue and suggest changes in features  then and there itself, it will save a lot of time

**Comment by aditya07389** [comment]
ill make changes asap !

**Pull request closed without merging**
