### PR TITLE
 added gsap to each product

### PR DESCRIPTION
**Pull request by Hamza1821**
# Pull Request Format
## Type of PR
- **Add X in the box to specify the improvement type.**
- [X] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
This pull request aims to [briefly describe what the pull request does, e.g., "add a new feature," "fix a bug," "improve documentation," etc.]. 

## Screenshots / Videos (if applicable)

**After:**

https://github.com/user-attachments/assets/eaa48fd9-b5de-45c4-bb0e-675abb8c9648

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by Hamza1821** [comment]
@sanjay-kv please merge this pr under gssoc-ext level 3

**Comment by Hamza1821** [comment]
mentors please accept my this pr before gssoc ends please accept it under gssoc-ext level 3
@JCarlosR  @sanjay-kv  @KrishPatel1205  @ygowthamr

**Comment by ygowthamr** [comment]
@ygowthamr 
Bro, I am not mentor

**Comment by KrishPatel1205** [comment]
> mentors please accept my this pr before gssoc ends please accept it under gssoc-ext level 3 @JCarlosR @sanjay-kv @KrishPatel1205 @ygowthamr

I am not a maintainer so unfortunately I can't help.

**Comment by Hamza1821** [comment]
please merge this

**Comment by ygowthamr** [comment]
@MastanSayyad @sanjay-kv pls look into this issue, pls help him.

**Comment by Hamza1821** [comment]
@MastanSayyad @aslams2020 @AKSHITHA-CHILUKA @sanjay-kv

please merge under level 3

**Comment by AKSHITHA-CHILUKA** [comment]
no level 3 for this 
image

**Comment by Hamza1821** [comment]
please merge

**Pull request closed without merging**
