### PR TITLE
B2T Fixes | Issue #205

### LINKED ISSUE #205: BackToTop Button scrolling is not smoth
### Description

Scrolling from bottom to top should be smooth by button

### Screenshots

https://github.com/user-attachments/assets/bb342917-ec98-4fa6-be5a-49de7ef89449

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

### PR DESCRIPTION
**Pull request by Shariq2003**
fix #205 
# Pull Request Format
## Type of PR
- **Add X in the box to specify the improvement type.**
- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Screenshots / Videos (if applicable)

https://github.com/user-attachments/assets/debb542b-29ce-4c4a-aa9c-1ecb28861965

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by Shariq2003** [comment]
@swaraj-das please review PR and merge

**Comment by swaraj-das** [comment]
@Shariq2003 Merge conflicts and also the scroll top button is not responding. Please solve.

**Comment by Shariq2003** [comment]
> @Shariq2003 Merge conflicts and also the scroll top button is not responding. Please solve.

Okay, fixing.....

**Comment by Shariq2003** [comment]
> @Shariq2003 Merge conflicts and also the scroll top button is not responding. Please solve.

@swaraj-das please review

**Comment by Shariq2003** [comment]
@swaraj-das please review this PR, this is in pending state since 3 days

**Comment by Shariq2003** [comment]
@swaraj-das please review and merge

**Comment by Shariq2003** [comment]
@AnitSarkar123 sir please review and merge this

**Comment by AnitSarkar123** [comment]
> @AnitSarkar123 sir please review and merge this

@swaraj-das

**Comment by Shariq2003** [comment]
> > @AnitSarkar123 sir please review and merge this
> 
> @swaraj-das

Actually he is not responding since last week

**Comment by Shariq2003** [comment]
@swaraj-das sir, please review and merge

**Comment by Shariq2003** [comment]
@MastanSayyad sir please review and merge this

**Comment by MastanSayyad** [comment]
@swaraj-das Review this PR and I noticed there are open PRs here make sure you buy some time and resolve all of them!

Also I don't have access to repo, kindly add me as a collaborator

**Comment by Shariq2003** [comment]
@sanjay-kv sir, please review this PR.

**Pull request closed without merging**
