### PR TITLE
Update style.css

### LINKED ISSUE #462: Add Hover Effects to Contact Us Form
### Description

The "Contact Us" form currently lacks hover effects, making it feel static. Adding hover effects to buttons and input fields will enhance the form's interactivity and user experience.

Expected Behavior:

- Apply hover effects to the submit button and input fields to make the form more engaging.
- Hover effects could include color changes or subtle shadow effects for visual feedback.

### Screenshots

image

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

### PR DESCRIPTION
**Pull request by neeru24**
### Pull Request: Add Hover Effect and Size Change to Card Element

**Description:** 
This pull request introduces a hover effect for the #card element, which enhances the user interface by providing a visual indication when the user hovers over the card. The changes include:

- Size Change: The card scales to 105% of its original size on hover, creating a subtle yet engaging effect.
- Box Shadow: A shadow is added to the card on hover, giving a sense of depth and elevating the card visually.

**Changes:**

- Updated CSS to include transitions for the #card element.
- Implemented hover effects that apply to the card, improving the overall user experience.

**Benefits:**

- Enhances visual feedback for users.
- Improves interactivity and engagement with the card element.

Please review the changes and merge it @swaraj-das 

fixes: #462 

### Before: No hover effect
image

### After: Added Hover effects
Note: Everything else remains the same. In the accompanying image, I attempted to replicate the main style for the changes, and the icons have not been removed.
image

### CODE REVIEW

**Comment by swaraj-das** [comment]
@neeru24 The item images and the total contact sections hover does not looking good.

**Comment by neeru24** [comment]
> @neeru24 The item images and the total contact sections hover does not looking good.

Okay, I'll work on it, give me some more time

**Comment by neeru24** [comment]
> @neeru24 The item images and the total contact sections hover does not looking good.

Can you tell me how can I improve the current hover effects? What exactly should I do, how you want it to be?

**Comment by swaraj-das** [comment]
> > @neeru24 The item images and the total contact sections hover does not looking good.
> 
> Can you tell me how can I improve the current hover effects? What exactly should I do, how you want it to be?

You can add hover only the on the contact inputs. No need to add hover effects to whole website. Keep it static.
If you want to add a new page for a specific product details, there you can add hover effects on the product and add 3d view or more.

**Comment by neeru24** [comment]
> > > @neeru24 The item images and the total contact sections hover does not looking good.
> > 
> > 
> > Can you tell me how can I improve the current hover effects? What exactly should I do, how you want it to be?
> 
> @neeru24 You can add hover only the on the contact inputs. No need to add hover effects to whole website. Keep it static. If you want to add a new page for a specific product details, there you can add hover effects on the product and add 3d view or more.

Got it. But I didn't applied hover effect to whole website, now I have updated the file, kindly check that.

**Pull request closed without merging**
