### PR TITLE
Fixed Cart Button #529

### PR DESCRIPTION
**Pull request by Ashish-Patnaik**
# Pull Request Format
## Type of PR
- **Add X in the box to specify the improvement type.**
- [X] Bug fix 

## Description
This pull request aims to fix the Cart icon which is not visible in the About-Page but now it fixed and designed in a way the repo owners asked

## Screenshots / Videos (if applicable)
**Before:**

**After:**

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by Ashish-Patnaik** [comment]
Kindly merge this PR @swaraj-das as I have done as you asked and I am very grateful for this contribution

**Comment by swaraj-das** [comment]
@Ashish-Patnaik You could not make it as the home page, if you can, then do it or leave it. I will do.

**Comment by Ashish-Patnaik** [comment]
@swaraj-das but I have made the cart icon exactly like the home page as you can see in the screenshots what's the problem if you can tell

**Comment by swaraj-das** [comment]
> @swaraj-das but I have made the cart icon exactly like the home page as you can see in the screenshots and already made a PR what's the problem if you can tell me I can correct

You can check the code of index.html..that cart button I made inside the button tag, but you made inside list.

**Comment by Ashish-Patnaik** [comment]
Ok I will correct as soon as possible

**Pull request closed without merging**
