### PR TITLE
ADD: Added descriptive titles for all three buttons

### PR DESCRIPTION
**Pull request by Sai-ganesh-0004**
# Pull Request Title
## Type of PR
- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update

## Description
This pull request aims to enhance the user interface by adding hover effects for three buttons: the Dark Mode toggle, the Chatbox icon, and the Scroll to Top button. The hover effects provide users with visual feedback, improving usability and accessibility.

## Before
- The buttons did not provide any feedback on hover, making it unclear to users that they were interactive.
IMG-20241013-WA0006
IMG-20241013-WA0005

IMG-20241013-WA0007

## After
- The buttons now display hover text, improving user understanding and interaction. The hover text appears above the buttons, clearly indicating their function.
IMG-20241013-WA0002
IMG-20241013-WA0004
IMG-20241013-WA0003
IMG-20241013-WA0008
IMG-20241013-WA0009

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### Additional Context
The hover effects were achieved using CSS pseudo-elements. I faced some challenges with positioning the hover text correctly, but adjustments were made to ensure that it appears neatly above the respective buttons. The implementation was tested in multiple browsers to ensure consistency.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by Sai-ganesh-0004** [comment]
once review
and let me know if any changes there

**Comment by swaraj-das** [comment]
@Sai-ganesh-0004 The chatbot button styling is changed, it should remain same.

**Comment by swaraj-das** [comment]
The 'chat with us' should in black type background like other namings you made

**Comment by Sai-ganesh-0004** [comment]
> The 'chat with us' should in black type background like other namings you made

Actually it is in black because as you directly bought it from the website chatbase i could not actually add descriptive title for as it is not an element in html or css so i installed a photo of the chatbox and when clicked on that it will open the chatbox

**Comment by Sai-ganesh-0004** [comment]
> @Sai-ganesh-0004 The chatbot button styling is changed, it should remain same.

Actually it is in black because as you directly bought it from the website chatbase i could not actually add descriptive title for as it is not an element in html or css so i installed a photo of the chatbox and when clicked on that it will open the chatbox

**Comment by Sai-ganesh-0004** [comment]
> > @Sai-ganesh-0004 The chatbot button styling is changed, it should remain same.
> 
> Actually it is in black because as you directly bought it from the website chatbase i could not actually add descriptive title for as it is not an element in html or css so i installed a photo of the chatbox and when clicked on that it will open the chatbox

If you want i could put the orange chatbox icon instead of black one

**Comment by Sai-ganesh-0004** [comment]
any updates

**Pull request closed without merging**
