### PR TITLE
aligned the return to top arrow

### PR DESCRIPTION
**Pull request by DevROHIT11**
# Pull Request Format
## Type of PR
- **Add X in the box to specify the improvement type.**
- [] Bug fix
- [ X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
This pull request aims to resolved the issue of overlapping of return to top arrow with chatbot which is now resolved 

## Screenshots / Videos (if applicable)
**Before:**
Screenshot (49)

**After:**
Screenshot (81)

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by DevROHIT11** [comment]
@swaraj-das it was great to contribute with you , resolving the issue was not that much easy but finally i completed with lots of efforts so could you please merge my pull request ASAP before the merge conflict occur . If possible please label it above level 1 
Thank you !!

**Comment by swaraj-das** [comment]
image
The scroll-top button’s position has been fixed, but its alignment still needs adjustment. Additionally, there's a CSS issue causing the 'Most Loved Products' section to collapse, and the visitor count in the footer is also affected.

**Comment by DevROHIT11** [comment]
> image
> The scroll-top button’s position has been fixed, but its alignment still needs adjustment. Additionally, there's a CSS issue causing the 'Most Loved Products' section to collapse, and the visitor count in the footer is also affected.

1. I just changed the property of .scroll-top which was for the  arrow . I don't change any other elements properties 
2 .What alignment Have to do can u please tell me?

**Comment by DevROHIT11** [comment]
@swaraj-das You are saying that I have to do changes for the affected css and visitor count???

**Comment by DevROHIT11** [comment]
@swaraj-das this issue is arise while merging someones PR I check From my side their are no changes happened

**Pull request closed without merging**
