### PR TITLE
added functionality to explore button

### PR DESCRIPTION
**Pull request by bhavanireddy57**
pull request:
issue no:#182 closes
I have added functionality to explore products button when clicking that it just goes to products.

https://github.com/user-attachments/assets/079aff3c-eb66-4bd4-b37b-5798058acd8c

### CODE REVIEW

**Comment by bhavanireddy57** [comment]
can you review it and let me know.

**Comment by bhavanireddy57** [comment]
Can you please review it and let me know

**Comment by swaraj-das** [comment]
Merge conflicts

**Comment by bhavanireddy57** [comment]
can you review it and let me know I have resolved the conflicts.

**Comment by bhavanireddy57** [comment]
Can you please review it and let me know

**Review by swaraj-das — APPROVED** [review]

**Pull request merged**
