### PR TITLE
dark mode toggle created ❗️

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
# Pull Request Format
## Type of PR
- [X] Feature enhancement
 
## Description
Created a dark mode toggle to switch between light and dark mode.

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.
Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
https://github.com/user-attachments/assets/b7b95122-4be6-4bf3-9662-7038434b340e

**Comment by T-Rahul-prabhu-38** [comment]
can you assign the level to the PR.

**Comment by swaraj-das** [comment]
@T-Rahul-prabhu-38

The navigation bar should also switch to dark mode for better consistency. Additionally, please place the button on the right side of the navigation for a cleaner layout. Also, ensure that the black fonts change to white or another relevant color in dark mode for improved visibility.

**Comment by T-Rahul-prabhu-38** [comment]
sure ill fix that

**Comment by swaraj-das** [comment]
@T-Rahul-prabhu-38 Please ensure to maintain the PR template. You didn’t provide the issue number or title, which makes it difficult to review the PR in relation to the issue. **Otherwise, we will not be able to review it**.

**Pull request closed without merging**
