### PR TITLE
Add eye button in password section done ! #326

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Fixed issue - #326

https://github.com/user-attachments/assets/34ecbef7-1e58-4d79-84fc-06779336075c

Screenshot 2024-10-14 235854
Screenshot 2024-10-14 235907

## Type of PR
- **Add X in the box to specify the improvement type.**
- [X] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [x] Other (specify): ___________  
- [ ] 
## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@AnitSarkar123 kindly add at least the level 2, because I implement something new..

**Comment by AnitSarkar123** [comment]
> @AnitSarkar123 merge my PR & kindly add at least level 2, because I implement something new..

Say it to @swaraj-das

**Comment by Subhajit-2023-44** [comment]
@swaraj-das merge my PR & kindly add at least level 2, because I implement something new..

**Comment by Subhajit-2023-44** [comment]
> > @AnitSarkar123 merge my PR & kindly add at least level 2, because I implement something new..
> 
> Say it to @swaraj-das

@AnitSarkar123 @swaraj-das please merge my pull request

otherwise i cannot start another task...

**Comment by Subhajit-2023-44** [comment]
@swaraj-das kindly upgrade the level 1 to 2, because I am implement something new..

Screenshot 2024-10-15 000929

**Pull request merged**
