### PR TITLE
integrate Apple iOS  sign in & fix  styles of the Testimonials

### PR DESCRIPTION
**Pull request by REHAN-18**
Issue #499  : Integrate Apple iOS Login & Style Fixes solve in Testimonials

## Type of PR
- **Add X in the box to specify the improvement type.**
- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
This pull request aims to integrate Apple iOS login functionality into the signup form and improve various styles for better user experience. The integration allows users to sign up using their Apple ID, enhancing security and user convenience. & 
change the Testimonials style now they look aesthetic

## Screenshots / Videos (if applicable)
**Before:**
- 
before
Screenshot 2024-10-17 at 1 03 37 AM

**After:**
- 
after
Screenshot 2024-10-17 at 12 51 49 AM

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### Additional Context
Integrating Apple Sign-In required setting up the Apple Developer account and configuring the necessary settings for client ID and redirect URI. During the style fixes, I focused on aligning input fields and buttons for a cleaner layout, improving the overall aesthetics of the signup page. I faced some challenges with cross-browser compatibility but have tested the final version across major browsers.
Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by swaraj-das** [comment]
@REHAN-18 Make the testimonial section toggle with light and dark mode.

**Comment by REHAN-18** [comment]
@swaraj-das ok !!!

**Comment by REHAN-18** [comment]
@swaraj-das done bro!!

**Comment by swaraj-das** [comment]
@REHAN-18 

image
The navbar collapsed. Fix it.

**Comment by REHAN-18** [comment]
@swaraj-das ok I will fix this !!

**Comment by REHAN-18** [comment]
@swaraj-das bro fix nav bar issue as well as testimonial section toggle with light and dark mode. 
Screenshot 2024-10-19 at 11 44 23 AM
Screenshot 2024-10-19 at 11 44 27 AM

check it! I have modified the readme  Added gssoc fest logo ....

**Comment by REHAN-18** [comment]
bro fix this issue as well as previous pls see it!!!

**Comment by REHAN-18** [comment]
Kindly merge this PR @swaraj-das as I have done as you asked and I am very grateful for this contribution

**Comment by REHAN-18** [comment]
@swaraj-das done bro SEE THIS MERGE MY PR as I fullfill all ur request & made a bugs free (resolved the issue )

**Comment by REHAN-18** [comment]
@swaraj-das BRO WHY RE U ignoring pr ...its take hardwork to raise a issue then raise a pr...we put effort to implement the the fix the bugs but ur not looking at the pr !!!

**Comment by REHAN-18** [comment]
@swaraj-das bro pls check this project their no conflict pls its I ve solve ur issue As you sAid

**Comment by REHAN-18** [comment]
@swaraj-das bro I ve raise this pr earlier but ur ignoring it >>> I ve done as you said merge it pls Issue #499
its take hardwork to do but you r ignoring it

**Comment by REHAN-18** [comment]
@MastanSayyad sir pls see this its almost 3 week but the maintainer is ignoring pr ....I ve done resolve the issue but it's not merged yet issue #507

**Comment by REHAN-18** [comment]
@MastanSayyad thanks sir!!

**Pull request merged**
