### PR TITLE
Connected frontEnd with BackEnd

### PR DESCRIPTION
**Pull request by Abhishek-TG18**
# Pull Request Format
## Type of PR
- **Add X in the box to specify the improvement type.**
- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
This PR implements the authentication feature for the application, including user signup, login, and session management using JWT tokens. The feature enables users to create an account, log in, and access protected routes.

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.

### Important Notes Before Reviewing the PR
**Environment Setup:**

Ensure that your local environment is set up correctly. You need to have Node.js and MongoDB installed and running.
Make sure to configure the necessary environment variables in your .env file, including:
PORT: Port for the backend server (default is 5000).
MONGODB_URL: Connection string for MongoDB.
SECRET: Secret key for JWT.
CLIENT_URL: URL for frontend access.

**CORS Configuration:**

The backend is configured to allow CORS requests from the frontend. Make sure the frontend is running on the specified CLIENT_URL for successful API calls.
Adjust the CORS settings if you are deploying the application or testing from different origins.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by Abhishek-TG18** [comment]
@swaraj-das 
Could you please explain me that what's wrong with this PR

**Comment by swaraj-das** [comment]
@AnitSarkar123 check it what's wrong

**Comment by AnitSarkar123** [comment]
> @swaraj-das 
> Could you please explain me that what's wrong with this PR

Could you please give a demo vedio of registration working

**Review by AnitSarkar123 — COMMENTED** [review]
Good but I require a demo vedio

**Comment by Abhishek-TG18** [comment]
https://github.com/user-attachments/assets/a602754c-b409-498a-8255-739d5dcef137


https://github.com/user-attachments/assets/5f2affa2-81e9-40b7-9c4e-258cb6eb2f63

Screenshot (103)

**Comment by Abhishek-TG18** [comment]
https://github.com/user-attachments/assets/31b691e1-c341-4441-98eb-db42d1189fa0


https://github.com/user-attachments/assets/25c27d5a-168f-493a-9468-1613a56bf313

Screenshot (103)

**Comment by Abhishek-TG18** [comment]
https://github.com/user-attachments/assets/f856a42d-5b20-4a3e-8aa1-65f85fde832e


https://github.com/user-attachments/assets/4ec8a6e6-cf92-4fa6-8f19-db5c7923d245

Screenshot (103)

**Comment by AnitSarkar123** [comment]
@Abhishek-TG18 very good 👍 I will merge it today

**Pull request merged**
