### PR TITLE
Add Star rating widget done ! #396

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature Star rating widget - #396

Done -

Screenshot 2024-10-16 170720

https://github.com/user-attachments/assets/58bd3a65-f14e-4e0a-b7c7-2d6103c5cb71

## Type of PR
- **Add X in the box to specify the improvement type.**
- [ ] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): ___________  
## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.
Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123

**Comment by AnitSarkar123** [comment]
> @swaraj-das @AnitSarkar123 

@swaraj-das please see it

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123 ??

**Comment by swaraj-das** [comment]
@Subhajit-2023-44 
image
Fix the stars.

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44  Fix the stars alignment.

@swaraj-das What ? But I add it properly.. please merge my pull request, otherwise I cannot start another task...

See -


https://github.com/user-attachments/assets/df21dd9b-dfea-4c17-96a4-79fa1c9bd993


Screenshot 2024-10-18 193731

**Comment by AnitSarkar123** [comment]
> > @Subhajit-2023-44  Fix the stars alignment.
> 
> @swaraj-das What ? But I add it properly.. please merge my pull request, otherwise I cannot start another task...
> 
> See -
> 
> 
> https://github.com/user-attachments/assets/df21dd9b-dfea-4c17-96a4-79fa1c9bd993
> 
> 
> Screenshot 2024-10-18 193731
> 
> 
> 

He said make it responsive

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 image Fix the stars alignment.

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123 please merge my pull request with level 3 or 2, otherwise I cannot start another task...

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123 please merge my pull request with level 3 or 2, otherwise I cannot start another task... 😞

**Comment by AnitSarkar123** [comment]
> @swaraj-das @AnitSarkar123 please merge my pull request with level 3 or 2, otherwise I cannot start another task... 😞

First make it responsive

**Comment by Subhajit-2023-44** [comment]
@AnitSarkar123 @swaraj-das 

> > > @swaraj-das @AnitSarkar123 please merge my pull request with level 3 or 2, otherwise I cannot start another task... 😞
> > 
> > 
> > First make it responsive
> 
> @AnitSarkar123 I didn't understand please tell me

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123 ??

**Comment by AnitSarkar123** [comment]
> @swaraj-das @AnitSarkar123 ??

I said you make the design responsive

**Comment by Subhajit-2023-44** [comment]
> > @swaraj-das @AnitSarkar123 ??
> 
> I said you make the design responsive

@AnitSarkar123 Responsive means you're asking to align properly, but I aligned the stars properly..

image

please merge my pull request, otherwise I cannot start another task... 😞

**Comment by AnitSarkar123** [comment]
> > > @swaraj-das @AnitSarkar123 ??
> > 
> > I said you make the design responsive
> 
> @AnitSarkar123 Responsive means you're asking to align properly, but I aligned the stars properly..
> 
> image
> 
> please merge my pull request, otherwise I cannot start another task... 😞

Sorry I can't Marge it ask @swaraj-das

**Comment by Subhajit-2023-44** [comment]
> > > > @swaraj-das @AnitSarkar123 ??
> > > 
> > > 
> > > I said you make the design responsive
> > 
> > 
> > @AnitSarkar123 Responsive means you're asking to align properly, but I aligned the stars properly..
> > image
> > please merge my pull request, otherwise I cannot start another task... 😞
> 
> Sorry I can't Marge it ask @swaraj-das

@swaraj-das please merge my pull request, otherwise I cannot start another task...

**Comment by Subhajit-2023-44** [comment]
@swaraj-das ??

**Pull request closed without merging**
