### PR TITLE
Dark Mode Toggle Button improved

### PR DESCRIPTION
**Pull request by Mayukh-Mandal2005**
## Type of PR
- [X] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
This pull request aims to improve the dark mode toggle button on the main website and make it more attractive than ever before with smooth transition effects and animations. 

## Screenshots
**Before:**
image

**After:**
image

image

## Checklist
- [X] I have performed a self-review of my code.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

Kindly add level tag, gssoc-ext, gssoc24 and hacktoberfest-accepted tag to this PR @swaraj-das sir.
Thank you for reviewing my pull request @swaraj-das sir!

### CODE REVIEW

**Comment by Mayukh-Mandal2005** [comment]
Hey @swaraj-das sir
Please look into this PR and merge it kindly with appropriate labels required such as GSSOC-ext,gssoc24,hacktoberfest-accepted and a level label as well.

**Comment by swaraj-das** [comment]
image
image
@Mayukh-Mandal2005 Please check your code. I appreciate your work. But fix these.

**Comment by Mayukh-Mandal2005** [comment]
@swaraj-das sir
I was assigned the issue to only change the UI of the toggle button.
I have just added the animation effects nothing else sir.
So, I do not think so that I might have done these sir.

**Comment by Mayukh-Mandal2005** [comment]
@swaraj-das sir
Sir I have made the necessary changes as asked by you.
The screenshots are as attached below -
image

image

Please see this PR and merge it and kindly also give a level label, gssoc-ext, gssoc24 and hacktoberfest-accepted labels @swaraj-das sir.

Thank You :)

**Comment by Mayukh-Mandal2005** [comment]
Hello @swaraj-das sir
Kindly state the reason for not merging the PR in the project and closing it without any action or comments.

**Pull request closed without merging**
