### PR TITLE
Fixed Navbar issue !

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello PR,
Fixed issue number - #267 & #265
& I also Fixed the search box issue in Navbar, which was not properly aligned.

Issue - 
Screenshot 2024-10-11 143820

but now Issue totally Fixed !
Screenshot 2024-10-11 143941
Screenshot 2024-10-11 143956

@swaraj-das PA please add the level 3 tag as I have solved the whole navbar issue properly.

## Type of PR
- **Add X in the box to specify the improvement type.**
- [X] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): ___________  

## Description
This pull request aims to [briefly describe what the pull request does, e.g., "add a new feature," "fix a bug," "improve documentation," etc.]. 

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123 merge it & please add the level 3 tag as I have solved the whole navbar issue properly.

**Comment by AnitSarkar123** [comment]
@Subhajit-2023-44 please resolve the conflicts

**Comment by Subhajit-2023-44** [comment]
@swaraj-das @AnitSarkar123 merge it & please add the level 3 tag as I have solved the whole navbar issue properly.

**Comment by Subhajit-2023-44** [comment]
@AnitSarkar123

**Comment by swaraj-das** [comment]
@Subhajit-2023-44 We cannot assign a level3 label for these types of fixes. However, if you implement something new, we can consider it for a level3 label. Another PR resolved the navigation issue more effectively than yours, so I have reverted your PR.

**Comment by Subhajit-2023-44** [comment]
Okay, but @swaraj-das @AnitSarkar123 PA kindly upgrade the level at least 1 to 2

**Pull request merged**
