### PR TITLE
Added email functionality to the contact form

### PR DESCRIPTION
**Pull request by AyushSharma72**
##Added email functionality to the contact form
## Type of PR
- **Add X in the box to specify the improvement type.**
- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
i added an api in the backend to send email to the admin of this project . and created a function in script.js file to connect the api in the backend

## Screenshots / Videos (if applicable)
forntend:
Screenshot (176)

Demo email:
WhatsApp Image 2024-10-08 at 16 00 10_e9cfc333

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

**please Add gssoc-ext and level2 label before merge**

### CODE REVIEW

**Comment by AnitSarkar123** [comment]
@AyushSharma72 please resolve the conflicts

**Comment by AyushSharma72** [comment]
> @AyushSharma72 please resolve the conflicts

Resolved

**Comment by swaraj-das** [comment]
@AyushSharma72 There has been conflict until now.

**Comment by AyushSharma72** [comment]
> @AyushSharma72 There has been conflict until now.

@swaraj-das

**Comment by AyushSharma72** [comment]
> > @AyushSharma72 There has been conflict until now.
> 
> @swaraj-das

after doing clean pr i got merge confilt 3 times please merge this PR @swaraj-das

**Comment by swaraj-das** [comment]
image
Not solved the conflicts.

**Comment by AyushSharma72** [comment]
> image Not solved the conflicts.

I will create another pr

**Comment by AyushSharma72** [comment]
> image Not solved the conflicts.

check new pr here @swaraj-das  [https://github.com/swaraj-das/Collect-your-GamingTools/pull/290](url)

**Pull request closed without merging**
