### PR TITLE
Issue #56: FEATURE: Implement "Add to Cart" Functionality for Existing Cart Option solved

### PR DESCRIPTION
**Pull request by Anwishta**
## Type of PR
- **Add X in the box to specify the improvement type.**
- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
This pull request aims to add a new feature "Cart" to the existing code base. The Cart functionality allows users to add items to their cart, enhancing the user experience by enabling them to view and manage their selected items before checkout.

## Screenshots / Videos (if applicable)
**Before:**
- The "Add to Cart" and "Buy now" button did not show any cart functionality, leaving users without a clear way to manage their selected items. A checkout button has also been added.

**After:**
- The "Add to Cart" and "Buy now" button now triggers a new page that displays the number of items added. Users can click the cart icon to view the contents, remove items making the shopping experience more intuitive and user-friendly.
###  Screenshot: 

Screenshot 2024-10-06 162843

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### Additional Context
The implementation of the Cart feature required integrating JavaScript functions to manage the cart state and dynamically update the UI. I faced challenges with ensuring that the cart updates correctly when items are added or removed, but these were resolved by utilizing local storage for persistence and clear function definitions for adding, removing, and displaying items. Moreover I had to integrate code within the existing code for triggering the new page without changing its styling.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by AnitSarkar123** [comment]
@Anwishta can you give a checkout button bellow the total price and also when someone click on the buy now button then it also add in the cart

**Comment by Anwishta** [comment]
ok

**Comment by swaraj-das** [comment]
@Anwishta Merge conflicts. Please resolve it.

**Comment by Anwishta** [comment]
@swaraj-das I've resolved the merge conflicts. Please check it

**Pull request closed without merging**
