### PR TITLE
preloaders added  issue #378

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
# Pull Request Format
the pre loaders have been added. issue #378  solved.
@swaraj-das can you please review this , i have one more PR to make , thank you.

https://github.com/user-attachments/assets/a8ef8ef7-be8a-4778-8363-aa6c783179a8

## PR Title
issue #378 

## Type of PR
- **Add X in the box to specify the improvement type.**
- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@swaraj-das i have raised a PR.

**Comment by swaraj-das** [comment]
@T-Rahul-prabhu-38 Remove the mouse animation. and solve conflicts.

**Comment by T-Rahul-prabhu-38** [comment]
@swaraj-das the changes have been made , please review this.

**Comment by T-Rahul-prabhu-38** [comment]
@swaraj-das the changes have been made , please review this.

**Comment by T-Rahul-prabhu-38** [comment]
@biswa2005 @swaraj-das can you please review this.

**Comment by biswa2005** [comment]
Ok good

**Comment by T-Rahul-prabhu-38** [comment]
@subhadipbhowmik can you review this PR. i have one more PR to make,.

**Comment by T-Rahul-prabhu-38** [comment]
@swaraj-das @AnitSarkar123 can you review this PR. i have one more PR to make,.

**Comment by T-Rahul-prabhu-38** [comment]
@swaraj-das @AnitSarkar123 can you review this PR. i have one more PR to make,.

**Comment by T-Rahul-prabhu-38** [comment]
@swaraj-das @AnitSarkar123 can you review this PR. i have one more PR to make,.

**Comment by T-Rahul-prabhu-38** [comment]
@swaraj-das @AnitSarkar123 can you review this PR. i have one more PR to make,.

**Comment by T-Rahul-prabhu-38** [comment]
@swaraj-das @AnitSarkar123 can you review this PR. i have one more PR to make,.

**Comment by swaraj-das** [comment]
@T-Rahul-prabhu-38 Preloader and scroll is not working

**Comment by T-Rahul-prabhu-38** [comment]
@swaraj-das i will fix this

**Pull request closed without merging**
