### PR TITLE
✨added ChatBot  (issue#165 solved)✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
# Pull Request Format
### Issue #0 :  issue #165

added the fully functional chatbot , it is fine tuned to this website.

https://github.com/user-attachments/assets/72dee469-2cb5-4310-b2e8-84648bef44e8

## Type of PR
- **Add X in the box to specify the improvement type.**
- [] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### Additional Context
[Provide any additional context about the changes, such as specific challenges you faced or decisions you made. This can help reviewers understand the rationale behind your changes.]

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@swaraj-das can you accept this PR , i have a new one coming.

**Comment by T-Rahul-prabhu-38** [comment]
@swaraj-das please review this PR.

**Comment by AnitSarkar123** [comment]
very good @T-Rahul-prabhu-38  I love it

**Comment by T-Rahul-prabhu-38** [comment]
can you merge this pr, i want push a new pr of another issue

**Comment by AnitSarkar123** [comment]
you can use https://getgist.com/   instead of chatbase

**Comment by T-Rahul-prabhu-38** [comment]
should i add this instead

**Comment by AnitSarkar123** [comment]
> should i add this instead

not required  actually chatbase also good  but it's free plan give less functionality

**Comment by T-Rahul-prabhu-38** [comment]
thank you , i was exploring new options aswell

**Pull request merged**
