### PR TITLE
Added PrValidator github workflow

### LINKED ISSUE #530: Adding github action workflow for PR validation
### Description

**The workflow checks consist of following steps-**

- Should check for the PR Description in the pull request
- Check for the issue number, if the PR is not addressing any issue it should include `Fixes #NEW`

@swaraj-das
Pls assign me this issue give me labels like gssoc-extd,hacktoberfest,level3

### Screenshots

image

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

### PR DESCRIPTION
**Pull request by ygowthamr**
**What i have done :**
- Solved Adding GitHub action workflow for PR validation

Fixes #530

@swaraj-das
Pls add me labels like gssoc-extd,level3,hacktoberfest.

### CODE REVIEW

**Comment by AnitSarkar123** [comment]
@ygowthamr 🤦🤦🤦🤦🤦🤦🤦 what said to you in #530 I said to you just fix it .

**Comment by ygowthamr** [comment]
@AnitSarkar123 

**That file does not exists in your git repo**

**The files that exist are:*** 
- image

**Comment by ygowthamr** [comment]
@AnitSarkar123 

The screen short which it is there in the issue is not from your repo it is from different repo i just kept it for reference

**Comment by AnitSarkar123** [comment]
> @AnitSarkar123 
> 
> The screen short which it is there in the issue is not from your repo it is from different repo i just kept it for reference. There is no such file like **PRValidator.yml** in your repo

@ygowthamr sorry for that


 I think you are saying about second file of the part

**Comment by ygowthamr** [comment]
@AnitSarkar123 

Ok no problem merge my pr

**Comment by AnitSarkar123** [comment]
> @AnitSarkar123 
> 
> Ok no problem merge my pr

@ygowthamr sorry we don't required this feature I said you about that.

**Comment by ygowthamr** [comment]
@AnitSarkar123 
Its your mistake right? you need to check properly before assigning. After assigning and after making pull request you should not say like this

**Comment by AnitSarkar123** [comment]
@ygowthamr ok I merge it

**Comment by ygowthamr** [comment]
@AnitSarkar123 
Thank you

**Comment by ygowthamr** [comment]
@AnitSarkar123 
Can you tell me exactly which error

**Comment by ygowthamr** [comment]
@AnitSarkar123 

Can you tell me exactly which error

**Pull request merged**
