### PR TITLE
Added navbar in contributor's page

### PR DESCRIPTION
**Pull request by charrviwadhwa**
# Pull Request Format
## Type of PR
- **Add X in the box to specify the improvement type.**
- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description

1. Added navbar with the logo and name of website.
2. Added Home and About us navigation pages in navbar.

## Screenshots / Videos (if applicable)
**Before:**
- There was a single home button.
Screenshot (1)

**After:**
- Added navbar with logo and navigation links which enhanced the website more.
Screenshot 2024-10-24 233655

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!
 if any changes required please let me know

### CODE REVIEW

**Comment by charrviwadhwa** [comment]
I have resolved this issue 
Please look forward to it

**Comment by charrviwadhwa** [comment]
Please merge this pr
I have resolved this issue

**Comment by swaraj-das** [comment]
image

@charrviwadhwa Fix the hover effect.

**Comment by charrviwadhwa** [comment]
I will fix

**Comment by charrviwadhwa** [comment]
Screenshot (4)

I have fixed the hover effect

**Comment by charrviwadhwa** [comment]
I have fixed this issue
Please merge the pr

**Comment by charrviwadhwa** [comment]
please merge the pr

**Comment by charrviwadhwa** [comment]
please merge  this pr @swaraj-das

**Review by swaraj-das — APPROVED** [review]

**Pull request merged**
