### PR TITLE
Login page revamped to match the retro theme

### PR DESCRIPTION
**Pull request by harbakshsinghbaath**
# Pull Request Format

## Type of PR
- **Improvement in style, fonts, colours and themes .**
- [ ] Bug fix
- [cool retro login button; background and a hazy login box ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
This pull request aims to [enhance the look of the login page making it more attractive to the eye.]. 

## Screenshots / Videos (if applicable)
Before
image

- [Describe the state before the changes - Missmatch in the fonts; the theme did not match the overall type of website; did not feel attractive; boring login ]

**After:**
image

- [Describe the state after the changes - Beter visuals; matches the theme of website; fun to look at; minute changes that go well together cohesively]

## Checklist
- **Add X in the box to specify.**
- [X ] I have performed a self-review of my code.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

### Additional Context
[Provide any additional context about the changes, such as specific challenges you faced or decisions you made. This can help reviewers understand the rationale behind your changes.]-Aesthetics are the only thoughts I had

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by swaraj-das** [comment]
@harbakshsinghbaath After reviewing the login page, I noticed that the background doesn't look very good as a gaming E-Com site, and the color and size of the login button are too large. Please fix it.

**Comment by harbakshsinghbaath** [comment]
sure will change the size of login button and if you have any ideas as to what you want as the background I'm open to ideas

**Comment by harbakshsinghbaath** [comment]
image
this image will match the colour gradients of the buttons we have in home page what do you think of it?

**Comment by harbakshsinghbaath** [comment]
image
fixed the size of login button just needed input on the background

**Comment by swaraj-das** [comment]
@harbakshsinghbaath

I recommend making the background slightly blurred to enhance the focus on the login form. Additionally, the button currently appears a bit large; reducing its size would improve the overall aesthetics.

Please sync your fork with the repo and make these changes. Once you’re done, you can also consider adding similar adjustments to the sign-up page.

**Comment by harbakshsinghbaath** [comment]
image
These are the final changes as you asked, the login button according to me now looks suitable in size and the background is a bit more understated so it doesn't take away the focus from login form 
as for the signup page id be delighted to revamp it too as I'll be able to maintain the theme but could you assign a new issue to me for it?

**Review by swaraj-das — APPROVED** [review]
PR looks good! Merging it now. 👍

**Comment by swaraj-das** [comment]
> (please do add hactober fest tag to me too) And I've synced the fork to my repository too.

Ok I check if there is not hactoberfest tag...I will add it.

**Comment by harbakshsinghbaath** [comment]
Thank you so much. Issue #69 is also opened by me and I would be glad if you'd assign it to me

**Comment by swaraj-das** [comment]
> Thank you so much. Issue #69 is also opened by me and I would be glad if you'd assign it to me

assigned already

**Pull request merged**
