### PR TITLE
Adding Animations effect in hole Project

### PR DESCRIPTION
**Pull request by 13Sharad**
# Pull Request Format
## Type of PR
- **Add X in the box to specify the improvement type.**
- [ ] Bug fix
- [YES] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
This pull request aims to add animation effects throughout the project and implement lazy loading for all images to enhance user experience. The animations improve visual appeal with smoother transitions, while lazy loading optimizes loading speed by ensuring images are loaded only when they are about to enter the viewport.

## Screenshots / Videos (if applicable)
**Before:**
-The website lacked visual effects and loaded all images immediately, resulting in slower performance and a static user experience.

**After:**
- The website now features smooth transitions and hover effects on buttons, making interactions more engaging. Additionally, lazy loading ensures that images load only as needed, improving overall loading speed and performance.

## Checklist
- **Add X in the box to specify.**
- [YES] I have performed a self-review of my code.
- [YES ] I have tested the changes thoroughly before submitting this pull request.
- [YES ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [YES ] I have commented my code, particularly in hard-to-understand areas.

### Additional Context
During implementation, I faced challenges in optimizing the animations to prevent any performance degradation. I ensured that the lazy loading feature works seamlessly with the existing content structure, enhancing the user experience without sacrificing speed.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by swaraj-das** [comment]
@13Sharad Make enhancement in loader. It is not good.

**Comment by 13Sharad** [comment]
@swaraj-das i Enhanced Loader Styling. please check this.

**Comment by 13Sharad** [comment]
@swaraj-das  please check i enhance the loader. and more things.

**Comment by 13Sharad** [comment]
@swaraj-das  please check i enhance the loader. and more things.

**Comment by 13Sharad** [comment]
@swaraj-das  please check i enhance the loader. and more things.

**Comment by 13Sharad** [comment]
@swaraj-das  please check i enhance the loader. and more things.

**Comment by 13Sharad** [comment]
@swaraj-das  please check i enhance the loader. and more things.

**Comment by 13Sharad** [comment]
@swaraj-das  please check i enhance the loader. and more

**Comment by 13Sharad** [comment]
@swaraj-das  please check i enhance the loader. and more.

**Comment by 13Sharad** [comment]
@swaraj-das  please check i enhance the loader. and more.

**Comment by 13Sharad** [comment]
@swaraj-das  please check i enhance the loader. and more.

**Comment by 13Sharad** [comment]
@swaraj-das  please check i enhance the loader. and more.

**Comment by 13Sharad** [comment]
@swaraj-das  please check i enhance the loader. and more.

**Comment by 13Sharad** [comment]
@swaraj-das  please check i enhance the loader. and more.

**Comment by 13Sharad** [comment]
@swaraj-das  please check i enhance the loader. and more.

**Comment by 13Sharad** [comment]
@swaraj-das  please merged this pull request.

**Comment by 13Sharad** [comment]
@swaraj-das  please merged this pull request.

**Comment by 13Sharad** [comment]
@swaraj-das  please merged this pull request.

**Comment by 13Sharad** [comment]
@swaraj-das  please merged this pull request.

**Comment by 13Sharad** [comment]
@swaraj-das  please merged this pull request.

**Comment by 13Sharad** [comment]
@swaraj-das  please merged this pull request.

**Comment by 13Sharad** [comment]
@swaraj-das  please merged this pull request.

**Comment by 13Sharad** [comment]
@swaraj-das please check i enhance the loader. and more.

**Comment by 13Sharad** [comment]
@swaraj-das please check i enhance the loader. and more.

**Comment by 13Sharad** [comment]
@swaraj-das please check i enhance the loader. and more.

**Comment by 13Sharad** [comment]
@swaraj-das please check i enhance the loader. and more.

**Comment by 13Sharad** [comment]
@swaraj-das please check i enhance the loader. and more.

**Comment by 13Sharad** [comment]
@swaraj-das please check i enhance the loader. and more.

**Review by swaraj-das — APPROVED** [review]

**Pull request merged**
