### PR TITLE
Added dockerfile docker-compose.yml 

### LINKED ISSUE #252: [Feature] Dockerize the Application
### Description

I want to add Dockerfile to the root of the project. A Dockerfile is a text file of instructions which are used to automate installation and configuration of a Docker image .

Adding Dockerfile to the root of the project will encourage image formation of the application using Docker and running the image in one's local environment without installing the dependencies.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

### PR DESCRIPTION
**Pull request by haseebzaki-07**
fixes #252 

command to build the image : docker build -t gamingtool .
command to run the image : docker run -d -p 8080:80 gamingtool; Start-Process "http://localhost:8080"

## Type of PR
- **Add X in the box to specify the improvement type.**
- [] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): ___________  

## Description
This PR dockerizes the Application

## Screenshots / Videos (if applicable)
Screenshot 2024-10-10 143324

The command starts the application inside docker conatainer and the application is available on port 8080.

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by haseebzaki-07** [comment]
hey @swaraj-das please review this PR

**Comment by swaraj-das** [comment]
@AnitSarkar123 Can you check it?

**Comment by AnitSarkar123** [comment]
> @AnitSarkar123 Can you check it?

Approved

**Comment by AnitSarkar123** [comment]
@haseebzaki-07 we don't want dockerfile because dockerfile deployment is very costly

**Comment by haseebzaki-07** [comment]
@AnitSarkar123 We can use dockerfile to set up project locally in development process it is totally optional if you do not want to use it in deployment/production. It makes development process much easier as one does not need to install dependencies locally and resolve conflicts . Docker takes care of that in every environment the project runs be it be LINUX/MAC/WINDOWS

**Comment by AnitSarkar123** [comment]
@haseebzaki-07 then can you please run mongodb on port 27017 on the docker-compose file and connect the app with the mongodb in a same network

**Comment by AnitSarkar123** [comment]
> @haseebzaki-07 then can you please run mongodb on port 27017 on the docker-compose file and connect the app with the mongodb in a same network 

I mean run the backend and the frontend at the same time

**Comment by haseebzaki-07** [comment]
@AnitSarkar123 sure I will check it!

**Comment by AnitSarkar123** [comment]
> @AnitSarkar123 sure I will check it!

Ko 👍

**Comment by haseebzaki-07** [comment]
hey @AnitSarkar123 I have updated the docker-compose file to connect frontend backend and database all in the same network.

Command to build and run the image : docker-compose up --build

**Comment by AnitSarkar123** [comment]
@haseebzaki-07 can you please give me a screenshot of the logs

**Comment by AnitSarkar123** [comment]
@haseebzaki-07 can you please give me a screenshot of the logs or picture then I will merge

**Comment by haseebzaki-07** [comment]
@AnitSarkar123 Here are the logs after docker builds the images and runs the application

Screenshot 2024-10-12 232404

Screenshot 2024-10-12 232327

Screenshot 2024-10-12 232302

**Comment by AnitSarkar123** [comment]
> @AnitSarkar123 Here are the logs after docker builds the images and runs the application
> 
> Screenshot 2024-10-12 232404
> 
> Screenshot 2024-10-12 232327
> 
> Screenshot 2024-10-12 232302
> 
> 

@haseebzaki-07 very good 👍

**Pull request merged**
